// <auto-generated />
namespace SmokeFreeApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class articleTagKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(articleTagKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202010150225373_articleTagKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
